CREATE DATABASE DUMMY;
USE DUMMY;

CREATE TABLE CUSTOMER_DETAILS (
CUSTOMER_ID INT,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
MOBILE_NUMBER BIGINT,
GENDER VARCHAR(20),
PAYMENT_ID INT,
PICKUP_LOCATION VARCHAR(20),
DROP_LOCATION VARCHAR(20),
EMAIL_ID VARCHAR(20));

insert into CUSTOMER_DETAILS values
(1,'raju','desai',82565454545,'male',101,'vizag','araku','asdfa@2gmail.com'),
(2,'ravi','shankar',82565454545,'male',102,'nellore','tirupathi','gasfa@gmail.com'),
(3,'karishma','dharmana',82565454545,'female',143,'chennai','srikakulam','thfa@gmail.com');

alter table customer_details alter column pickup_location varchar(20);
alter table customer_details alter column drop_location varchar(20);
ALTER TABLE CUSTOMER_DETAILS drop CONSTRAINT FOR_KEY ;





CREATE TABLE DRIVER_DETAILS (
DRIVER_ID INT,
CUSTOMER_ID INT,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
MOBILE_NUMBER BIGINT,
GENDER VARCHAR(20));






CREATE TABLE PAYMENT_DETAILS (
PAYMENT_ID INT,
CUSTOMER_ID INT,
PAYMENT_TYPE VARCHAR(20),
PAYMENT_METHOD VARCHAR(20));





ALTER TABLE CUSTOMER_DETAILS ADD CONSTRAINT PRIM_KEY PRIMARY KEY (CUSTOMER_ID);
ALTER TABLE DRIVER_DETAILS ADD CONSTRAINT PRIM_KEY1 PRIMARY KEY (DRIVER_ID);
ALTER TABLE PAYMENT_DETAILS ADD CONSTRAINT PRIM_KEY2 PRIMARY KEY (PAYMENT_ID);

ALTER TABLE CUSTOMER_DETAILS ADD CONSTRAINT FOR_KEY FOREIGN KEY(PAYMENT_ID) REFERENCES PAYMENT_DETAILS(PAYMENT_ID);
ALTER TABLE DRIVER_DETAILS ADD CONSTRAINT FOR_KEY1 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_DETAILS(CUSTOMER_ID);

ALTER TABLE CUSTOMER_DETAILS ALTER COLUMN CUSTOMER_ID INT NOT NULL ;
ALTER TABLE DRIVER_DETAILS ALTER COLUMN DRIVER_ID INT NOT NULL ;
ALTER TABLE PAYMENT_DETAILS ALTER COLUMN PAYMENT_ID INT NOT NULL ;
ALTER TABLE PAYMENT_DETAILS DROP COLUMN CUSTOMER_ID;

select* from CUSTOMER_DETAILS;
select* from DRIVER_DETAILS;
select* from PAYMENT_DETAILS;